Adding MERGE command instructions when updating contact
takenet/blip-docs pull request #77
Opened 2021-12-23 15:03 UTC by luccanog

2021-12-23 15:27 UTC, mathiasfk requested changes

2021-12-23 15:27 UTC, mathiasfk commented on source/includes/en/documents/contact.md
> +| taxDocument | The contact's identification document code. | string |
"document number" sounds more natural to me

2021-12-23 15:27 UTC, mathiasfk commented on source/includes/en/documents/contact.md
> +| taxDocument | The contact's identification document code. | string |
Why did you change from "client" to "contact" only here? The terminology should be consistent throughout the documentation.

2021-12-23 15:27 UTC, mathiasfk commented on source/includes/en/extensions/contacts.md
> +When updating a contact using the <strong>SET</strong> command, not passing one of the contact's existing property in the request will delete it.
properties

2021-12-23 15:27 UTC, mathiasfk commented on source/includes/en/extensions/contacts.md
> +If the contact already has the <i>address</i> property and you don't pass It in the request, the contact's <i>adress</i> information <strong>is going to be deleted.</strong>
I don't think "It" should be uppercase here.

2021-12-23 15:27 UTC, mathiasfk commented on source/includes/en/extensions/contacts.md
> +If the contact has (or has not) the <i>name</i> property and you send It in the request, the contact's <i>name</i> value <strong>will be updated.</strong>
Same here

2021-12-23 15:27 UTC, mathiasfk commented on source/includes/en/extensions/contacts.md
> +If the contact has (or has not) the <i>name</i> property and you send It in the request, the contact's <i>name</i> value <strong>will be updated.</strong>
I think that "(or has not)" doesn't really help the example in this case. In fact it makes it a bit more confusing.

2021-12-23 15:27 UTC, mathiasfk commented on source/includes/en/extensions/contacts.md
> +In order to update information about a chatbot's client, it is possible to save and update data using **contacts extension**.
I feel like this text is repeated. Is it in the right place?

2021-12-27 16:39 UTC, luccanog commented on source/includes/en/extensions/contacts.md
> +In order to update information about a chatbot's client, it is possible to save and update data using **contacts extension**.
In the first text, it's written `store `intead of `update`. Do you have any suggestion to improve it?

2021-12-27 16:39 UTC, luccanog commented on source/includes/en/documents/contact.md
> +| taxDocument | The contact's identification document code. | string |
solved

2021-12-27 16:47 UTC, luccanog commented on source/includes/en/extensions/contacts.md
> +When updating a contact using the <strong>SET</strong> command, not passing one of the contact's existing property in the request will delete it.
fixed

2021-12-27 16:47 UTC, luccanog commented on source/includes/en/extensions/contacts.md
> +If the contact already has the <i>address</i> property and you don't pass It in the request, the contact's <i>adress</i> information <strong>is going to be deleted.</strong>
sure

2021-12-27 16:47 UTC, luccanog commented on source/includes/en/extensions/contacts.md
> +If the contact has (or has not) the <i>name</i> property and you send It in the request, the contact's <i>name</i> value <strong>will be updated.</strong>
I tried something, please check out

2021-12-27 16:48 UTC, luccanog commented on source/includes/en/extensions/contacts.md
> +In order to update information about a chatbot's client, it is possible to save and update data using **contacts extension**.
I tried something, please check out

2021-12-27 16:51 UTC, luccanog commented on source/includes/en/extensions/contacts.md
> +If the contact has (or has not) the <i>name</i> property and you send It in the request, the contact's <i>name</i> value <strong>will be updated.</strong>
I tried to improve it, please check out

2021-12-27 16:51 UTC, luccanog commented on source/includes/en/extensions/contacts.md
> +If the contact has (or has not) the <i>name</i> property and you send It in the request, the contact's <i>name</i> value <strong>will be updated.</strong>
fixed

2021-12-27 16:52 UTC, luccanog commented on source/includes/en/documents/contact.md
> +| taxDocument | The contact's identification document code. | string |
I've updated the other table to use the "contact" word

2021-12-27 17:02 UTC, rodrigoxavier commented on source/includes/en/documents/contact.md
> +| taxDocument | The contact's identification document number. | string |
In my opinion that sentence could be better, I guess is confusing to understand if you're a new person reading this.
I suggest something like: `The contact's unique identification. For example, document number.`

2021-12-27 17:15 UTC, luccanog commented on source/includes/en/documents/contact.md
> +| taxDocument | The contact's identification document number. | string |
There is another table in another file with examples. This table is only the properties simples descriptions

2021-12-27 17:15 UTC, yuri-aeks commented
Could you update the "run postman collection" buttom? Only the share link has to be updated

2021-12-27 17:17 UTC, luccanog commented on source/includes/en/documents/contact.md
> +| taxDocument | The contact's identification document number. | string |
@rodrigoxavier  Please, check the contacts.md file , and tell me what do you think.

2021-12-27 17:51 UTC, JoaoCMotaJr approved these changes

2021-12-28 11:47 UTC, mathiasfk approved these changes

2021-12-28 14:47 UTC, merged